name: check-pull

on:
  pull_request:
    branches: [ "main" ]
  
  jobs:
    build:

      runs-on: ubuntu-latest

      steps:
        - name: checkout
          uses: actions/checkout@v3

        - name: setup Node.js 16.x
          uses: actions/setup-node@v3
          with:
            node-version: 16.x
            cach: "npm"
          
        - name: install dependencies
          run: yarn install --immutable --prefer-offline

        - name: running ci
          run: yarn ci